services:
  app:
    x-defang-llm: true
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgres://postgres:${POSTGRES_PASSWORD}@database:5432/postgres
      - DB_SSL=true #set this to false if deploying to defang playground
      - GITHUB_TOKEN #optional, remove this line if unused
      - DEFANG_PROVIDER # use "gcp" when deploying to Google Cloud, "aws" when deploying to AWS
      - DEFANG_GCP_PROJECT # change to your GCP project when deploying to Google Cloud
      - DEFANG_GCP_LOCATION #should be us-central1 when deploying to Google Cloud, else change to your perferred location
      - LLM_MODEL=anthropic.claude-3-5-sonnet-20241022-v2:0 #gemini-2.5-flash for GCP, anthroipc.claude-3-5-sonnet-20241022-v2 for AWS
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 3000
        published: 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      - database

  database:
    image: postgres:16
    x-defang-postgres: true # comment when deploying to defang playground
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - mode: host
        target: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
