services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgres://postgres:${POSTGRES_PASSWORD}@database:5432/postgres
      - DB_SSL=true
      - NODE_ENV=production
      - GOOGLE_GENERATIVE_AI_API_KEY
      - GITHUB_TOKEN
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 3000
        published: 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      - database

  database:
    image: postgres:16
    x-defang-postgres: true
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - mode: host
        target: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
