name: nocodb
services:
  nocodb:
    image: nocodb/nocodb:0.252.0
    environment:
      NC_DB: null
      NC_S3_ENDPOINT: null
      NC_S3_BUCKET_NAME: null
      NC_S3_REGION: null
      NC_S3_ACCESS_KEY: null
      NC_S3_ACCESS_SECRET: null
    ports:
      - target: 8080
        published: 8080
        mode: ingress
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 512M
