name: django-railpack
services:
  django:
    restart: unless-stopped
    build:
      context: ./app
    ports:
      - mode: ingress
        target: 8000
    environment:
      - DEBUG=False
    command:
      - python manage.py migrate && python manage.py createsuperauto && gunicorn defang_sample.wsgi:application
        --bind 0.0.0.0:8000
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 512M
