name: javalin
services:
  javalin-app:
    build:
      context: ./app
    ports:
    - target: 7000
      published: 7000
      mode: ingress
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:7000/
