[project]
name = "mcp-client"
version = "0.1.0"
description = "MCP client to query Anthropic's Claude AI and utilize MCP tools to augment response."
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
