<<<<<<< HEAD
version: "3.9"
=======
>>>>>>> origin/main
name: slack-invite-bot
services:
  bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
    environment:
      - SLACK_TOKEN
      - SLACK_CHANNEL_ID
